export const fruits: Fruit[] = [
  {
    id: "fruit001",
    name: "Apple",
    emoji: "🍎",
    backgroundColor: "#ffcccb", // light pastel red
    image: "https://example.com/images/apple.jpg",
    season: ["September", "October", "November"],
    vitamins: ["Vitamin C", "Vitamin K"],
    nutrients: {
      fiber: 4.0,
      sugar: 19.0,
      carbohydrates: 25.0,
      fat: 0.3,
      protein: 0.5,
    },
    healthScore: 80,
    benefits: ["Good for heart health", "Supports digestion"],
    risks: ["May cause bloating if consumed in excess"],
    regionAvailability: ["Europe", "North America"],
    storageTips: "Store in a cool, dark place or refrigerate.",
    recipes: ["Apple pie", "Apple crumble"],
  },
  {
    id: "fruit002",
    name: "Strawberry",
    emoji: "🍓",
    backgroundColor: "#ffb3b3", // light pastel red
    image: "https://example.com/images/strawberry.jpg",
    season: ["May", "June", "July"],
    vitamins: ["Vitamin C", "Folate"],
    nutrients: {
      fiber: 2.0,
      sugar: 7.0,
      carbohydrates: 8.0,
      fat: 0.3,
      protein: 0.8,
    },
    healthScore: 85,
    benefits: ["Rich in antioxidants", "Good for skin health"],
    risks: ["May cause allergies in sensitive individuals"],
    regionAvailability: ["Europe", "North America"],
    storageTips: "Keep in the refrigerator and consume within 2-3 days.",
    recipes: ["Strawberry jam", "Strawberry shortcake"],
  },
  {
    id: "fruit003",
    name: "Banana",
    emoji: "🍌",
    backgroundColor: "#ffffcc", // light pastel yellow
    image: "https://example.com/images/banana.jpg",
    season: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    vitamins: ["Vitamin B6", "Vitamin C"],
    nutrients: {
      fiber: 2.6,
      sugar: 12.0,
      carbohydrates: 27.0,
      fat: 0.3,
      protein: 1.3,
    },
    healthScore: 78,
    benefits: ["Provides energy", "Supports heart health"],
    risks: ["May cause constipation if overripe"],
    regionAvailability: ["Tropics", "Asia", "South America"],
    storageTips: "Store at room temperature; refrigerate when ripe.",
    recipes: ["Banana bread", "Banana smoothies"],
  },
  {
    id: "fruit004",
    name: "Cherry",
    emoji: "🍒",
    backgroundColor: "#ffb3b3", // light pastel red
    image: "https://example.com/images/cherry.jpg",
    season: ["June", "July"],
    vitamins: ["Vitamin C", "Vitamin A"],
    nutrients: {
      fiber: 1.6,
      sugar: 8.0,
      carbohydrates: 16.0,
      fat: 0.2,
      protein: 1.0,
    },
    healthScore: 82,
    benefits: ["Rich in antioxidants", "Supports sleep health"],
    risks: ["May cause digestive issues if overeaten"],
    regionAvailability: ["Europe", "North America"],
    storageTips: "Refrigerate and consume within 5 days.",
    recipes: ["Cherry pie", "Cherry jam"],
  },
  {
    id: "fruit005",
    name: "Pear",
    emoji: "🍐",
    backgroundColor: "#b3e6b3", // light pastel green
    image: "https://example.com/images/pear.jpg",
    season: ["September", "October", "November"],
    vitamins: ["Vitamin C", "Vitamin K"],
    nutrients: {
      fiber: 3.1,
      sugar: 10.0,
      carbohydrates: 26.0,
      fat: 0.2,
      protein: 0.6,
    },
    healthScore: 80,
    benefits: ["Aids digestion", "Good for heart health"],
    risks: ["May cause bloating in sensitive individuals"],
    regionAvailability: ["Europe", "Asia"],
    storageTips: "Store at room temperature; refrigerate once ripe.",
    recipes: ["Pear tart", "Poached pears"],
  },
  {
    id: "fruit006",
    name: "Watermelon",
    emoji: "🍉",
    backgroundColor: "#ffb3b3", // light pastel red
    image: "https://example.com/images/watermelon.jpg",
    season: ["June", "July", "August"],
    vitamins: ["Vitamin C", "Vitamin A"],
    nutrients: {
      fiber: 0.4,
      sugar: 6.0,
      carbohydrates: 8.0,
      fat: 0.2,
      protein: 0.6,
    },
    healthScore: 70,
    benefits: ["Keeps you hydrated", "Good for skin health"],
    risks: ["May cause diarrhea if consumed in excess"],
    regionAvailability: ["Africa", "Asia", "Americas"],
    storageTips: "Keep at room temperature; refrigerate after cutting.",
    recipes: ["Watermelon salad", "Watermelon juice"],
  },
  {
    id: "fruit007",
    name: "Orange",
    emoji: "🍊",
    backgroundColor: "#ffcc80", // light pastel orange
    image: "https://example.com/images/orange.jpg",
    season: ["November", "December", "January", "February", "March", "April"],
    vitamins: ["Vitamin C", "Vitamin A"],
    nutrients: {
      fiber: 3.1,
      sugar: 12.0,
      carbohydrates: 15.0,
      fat: 0.2,
      protein: 1.0,
    },
    healthScore: 85,
    benefits: ["Boosts immune system", "Good for skin health"],
    risks: ["May cause heartburn in sensitive individuals"],
    regionAvailability: ["Global"],
    storageTips: "Store in a cool, dry place or refrigerate.",
    recipes: ["Orange juice", "Orange salad"],
  },
  {
    id: "fruit008",
    name: "Grapes",
    emoji: "🍇",
    backgroundColor: "#d1b3ff", // light pastel purple
    image: "https://example.com/images/grapes.jpg",
    season: ["July", "August", "September"],
    vitamins: ["Vitamin C", "Vitamin K"],
    nutrients: {
      fiber: 0.9,
      sugar: 16.0,
      carbohydrates: 17.0,
      fat: 0.2,
      protein: 0.6,
    },
    healthScore: 78,
    benefits: ["Rich in antioxidants", "Promotes heart health"],
    risks: ["May cause digestive issues if overeaten"],
    regionAvailability: ["Europe", "North America", "Asia"],
    storageTips: "Refrigerate in a perforated plastic bag.",
    recipes: ["Grape juice", "Grape jelly"],
  },
  {
    id: "fruit009",
    name: "Peach",
    emoji: "🍑",
    backgroundColor: "#ffcc99", // light pastel orange
    image: "https://example.com/images/peach.jpg",
    season: ["June", "July", "August"],
    vitamins: ["Vitamin C", "Vitamin A"],
    nutrients: {
      fiber: 1.5,
      sugar: 13.0,
      carbohydrates: 15.0,
      fat: 0.4,
      protein: 0.9,
    },
    healthScore: 80,
    benefits: ["Good for digestion", "Supports skin health"],
    risks: ["May cause allergic reactions in sensitive individuals"],
    regionAvailability: ["Europe", "North America"],
    storageTips: "Store at room temperature; refrigerate once ripe.",
    recipes: ["Peach cobbler", "Peach smoothie"],
  },
  {
    id: "fruit010",
    name: "Pineapple",
    emoji: "🍍",
    backgroundColor: "#ffffb3", // light pastel yellow
    image: "https://example.com/images/pineapple.jpg",
    season: ["March", "April", "May", "June", "July"],
    vitamins: ["Vitamin C", "Vitamin A"],
    nutrients: {
      fiber: 2.3,
      sugar: 16.0,
      carbohydrates: 22.0,
      fat: 0.1,
      protein: 0.5,
    },
    healthScore: 82,
    benefits: ["Boosts immune system", "Aids digestion"],
    risks: ["May cause mouth irritation in some people"],
    regionAvailability: ["Tropics", "South America", "Asia"],
    storageTips: "Refrigerate whole or store at room temperature until ripe.",
    recipes: ["Pineapple upside-down cake", "Pineapple salsa"],
  },
];
