export const vegetables: Vegetable[] = [
  {
    id: "veg001",
    name: "Carrot",
    emoji: "🥕",
    backgroundColor: "#ffecb3",
    image: "https://example.com/images/carrot.jpg",
    season: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    vitamins: ["Vitamin A", "Vitamin K", "Vitamin C"],
    nutrients: {
      fiber: 2.8,
      protein: 0.9,
      carbohydrates: 9.6,
      sugar: 4.7,
      fat: 0.2,
    },
    healthScore: 85,
    benefits: ["Good for eyesight", "Supports immune health"],
    risks: ["May cause allergies in some people"],
    regionAvailability: ["Europe", "Asia"],
    storageTips: "Store in a cool, dry place or refrigerate.",
    recipes: ["Carrot soup", "Carrot salad"],
  },
  {
    id: "veg002",
    name: "Spinach",
    emoji: "🌿",
    backgroundColor: "#d0f0c0",
    image: "https://example.com/images/spinach.jpg",
    season: [
      "March",
      "April",
      "May",
      "June",
      "September",
      "October",
      "November",
    ],
    vitamins: ["Vitamin A", "Vitamin C", "Vitamin K"],
    nutrients: {
      fiber: 2.2,
      protein: 2.9,
      carbohydrates: 3.6,
      sugar: 0.4,
      fat: 0.4,
    },
    healthScore: 90,
    benefits: ["Rich in iron", "Supports bone health"],
    risks: ["High oxalate content can affect kidney health"],
    regionAvailability: ["Europe", "North America"],
    storageTips: "Store in the refrigerator, wrapped in a damp paper towel.",
    recipes: ["Spinach quiche", "Green smoothies"],
  },
  {
    id: "veg003",
    name: "Broccoli",
    emoji: "🥦",
    backgroundColor: "#d0f0c0",
    image: "https://example.com/images/broccoli.jpg",
    season: ["April", "May", "June", "July", "August", "September", "October"],
    vitamins: ["Vitamin C", "Vitamin K", "Vitamin A"],
    nutrients: {
      fiber: 2.6,
      protein: 2.8,
      carbohydrates: 6.6,
      sugar: 1.7,
      fat: 0.4,
    },
    healthScore: 88,
    benefits: ["Rich in antioxidants", "Supports heart health"],
    risks: ["May cause gas in some individuals"],
    regionAvailability: ["Europe", "North America"],
    storageTips: "Store in the refrigerator for up to 5 days.",
    recipes: ["Broccoli stir-fry", "Broccoli soup"],
  },
  {
    id: "veg004",
    name: "Potato",
    emoji: "🥔",
    backgroundColor: "#e0c2b0",
    image: "https://example.com/images/potato.jpg",
    season: ["July", "August", "September"],
    vitamins: ["Vitamin B6", "Vitamin C"],
    nutrients: {
      fiber: 2.1,
      protein: 2.0,
      carbohydrates: 17.5,
      sugar: 0.8,
      fat: 0.1,
    },
    healthScore: 75,
    benefits: ["Provides energy", "Supports digestive health"],
    risks: ["May cause weight gain if consumed in excess"],
    regionAvailability: ["Europe", "Asia", "Americas"],
    storageTips: "Store in a cool, dark, and dry place.",
    recipes: ["Mashed potatoes", "Potato gratin"],
  },
  {
    id: "veg005",
    name: "Bell Pepper",
    emoji: "🌶️",
    backgroundColor: "#f7e4e1",
    image: "https://example.com/images/bellpepper.jpg",
    season: ["June", "July", "August", "September"],
    vitamins: ["Vitamin C", "Vitamin A", "Vitamin E"],
    nutrients: {
      fiber: 1.7,
      protein: 0.9,
      carbohydrates: 6.0,
      sugar: 4.2,
      fat: 0.2,
    },
    healthScore: 92,
    benefits: ["Boosts immune health", "Rich in antioxidants"],
    risks: ["May cause allergies in sensitive individuals"],
    regionAvailability: ["Europe", "South America"],
    storageTips: "Store in the refrigerator for up to 7 days.",
    recipes: ["Stuffed peppers", "Pepper stir-fry"],
  },
  {
    id: "veg006",
    name: "Cucumber",
    emoji: "🥒",
    backgroundColor: "#d0f0c0",
    image: "https://example.com/images/cucumber.jpg",
    season: ["June", "July", "August", "September"],
    vitamins: ["Vitamin K", "Vitamin C"],
    nutrients: {
      fiber: 0.5,
      protein: 0.6,
      carbohydrates: 3.6,
      sugar: 1.7,
      fat: 0.1,
    },
    healthScore: 80,
    benefits: ["Hydrates the body", "Supports skin health"],
    risks: ["May cause indigestion if eaten in excess"],
    regionAvailability: ["Europe", "Asia"],
    storageTips: "Store in the refrigerator, preferably in a vegetable drawer.",
    recipes: ["Cucumber salad", "Cucumber sandwiches"],
  },
  {
    id: "veg007",
    name: "Tomato",
    emoji: "🍅",
    backgroundColor: "#ffcccc",
    image: "https://example.com/images/tomato.jpg",
    season: ["June", "July", "August", "September"],
    vitamins: ["Vitamin C", "Vitamin K", "Vitamin A"],
    nutrients: {
      fiber: 1.2,
      protein: 1.0,
      carbohydrates: 3.9,
      sugar: 2.6,
      fat: 0.2,
    },
    healthScore: 85,
    benefits: ["Rich in antioxidants", "Supports heart health"],
    risks: ["May cause acid reflux in some individuals"],
    regionAvailability: ["Europe", "North America"],
    storageTips: "Store at room temperature until ripe, then refrigerate.",
    recipes: ["Tomato sauce", "Caprese salad"],
  },
  {
    id: "veg008",
    name: "Zucchini",
    emoji: "🥒",
    backgroundColor: "#d0f0c0",
    image: "https://example.com/images/zucchini.jpg",
    season: ["June", "July", "August", "September"],
    vitamins: ["Vitamin C", "Vitamin A"],
    nutrients: {
      fiber: 1.0,
      protein: 1.0,
      carbohydrates: 3.1,
      sugar: 2.5,
      fat: 0.3,
    },
    healthScore: 88,
    benefits: ["Promotes healthy digestion", "Supports heart health"],
    risks: ["Can cause mild bloating in some individuals"],
    regionAvailability: ["Europe", "North America"],
    storageTips: "Store in the refrigerator for up to a week.",
    recipes: ["Zucchini fritters", "Zucchini noodles"],
  },
];
